---
title: "Lab# 1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.



```{r data}

## ----------------- PROBLEMA 1 ------------------------------------
library(readxl)
library(readr)
library(tidyverse)
library(tidytext)
library(dbplyr)


data_unificada <- read_csv("data_unificada.csv")
head(data_unificada)

paste("El numero de filas del archivo es :" ,nrow(data_unificada) )
paste("El numero de columnas del archivo es :" ,ncol(data_unificada) )

## ----------------- PROBLEMA 2 ------------------------------------

lista_vectores <- list(vec1 = c(1,2,3,3,4,4,5,8,9,7) , 
                       vec2 = c(3,4,3,3,11,16,3,20) , 
                       vec3 = c(22,35,35,21,21,35,99))

calculo_moda <- function(vector) {
  frecuencias <- table(vector)
  moda <- as.numeric(names(frecuencias[frecuencias == max(frecuencias)]))
  return(moda)
}

moda_vectores <- lapply(lista_vectores, calculo_moda)
moda_vectores

## ----------------- PROBLEMA 3 ------------------------------------

datos_parqueo2019 <- read_delim("parqueo2019.txt" , "|")
head(datos_parqueo2019, 10)

```




